######################################################################
# Automatically generated by qmake (3.1) Sat Apr 12 15:58:28 2025
######################################################################

INCLUDEPATH += /opt/homebrew/opt/qt/include /Users/wangchao/dev/computational-geometry/boost_org/boost
QT += core opengl widgets
LIBS += -F/opt/homebrew/Cellar/qt@5/5.15.16_1/lib \
        -framework QtOpenGL \
        -framework QtWidgets \
        -framework QtGui \
        -framework QtCore
QMAKE_MACOSX_DEPLOYMENT_TARGET = 13.0  # Match Qt's tested SDK version
TEMPLATE = app
TARGET = voronoi_visualizer

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += voronoi_visual_utils.hpp
SOURCES += voronoi_visualizer.cpp
